# Generated by Django 5.0.6 on 2024-07-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_usuario', models.CharField(choices=[('Personal', 'Personal'), ('Aportador', 'Aportador')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id_fundacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion_principal', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MandatoAporte',
            fields=[
                ('id_mandato_aporte', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_tarjeta', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id_residente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_personal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aportador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inicio.usuario')),
                ('numero_cel', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Aportadores',
            },
            bases=('inicio.usuario',),
        ),
        migrations.CreateModel(
            name='AccionMedica',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.fichamedica')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id_aporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.mandatoaporte')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMedicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.residente'),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_familiar', models.CharField(max_length=100)),
                ('apellido_familiar', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('parentesco', models.CharField(max_length=50)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.residente')),
            ],
        ),
        migrations.AddField(
            model_name='residente',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sede'),
        ),
        migrations.CreateModel(
            name='CompraInsumos',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sede')),
            ],
        ),
        migrations.AddField(
            model_name='mandatoaporte',
            name='aportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.aportador'),
        ),
        migrations.CreateModel(
            name='AporteHistorico',
            fields=[
                ('id_aporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('id_aportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.aportador')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inicio.usuario')),
                ('telefono', models.CharField(max_length=20)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.sede')),
                ('tipo_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.tipopersonal')),
            ],
            options={
                'verbose_name_plural': 'Personales',
            },
            bases=('inicio.usuario',),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
